    steps:
      - uses: actions/checkout@v2
      - name: Setup Conda
        uses: s-weigand/setup-conda@v1
        with:
          update-conda: true
          python-version: ${{ matrix.python-version }}
          conda-channels: anaconda, conda-forge
          activate-environment: pysoftk_env
          environment-file: environment.yml
          auto-activate-base: false
