- name: Build docs
        run: |
          python -m pip install sphinx!=5.1.0 sphinx_rtd_theme
          cd docs
          bash make_apidoc.sh
          make html
          cd ..
        if: matrix.documentation
      - name: Deploy docs
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/build/html
          force_orphan: true
        if: matrix.documentation && github.ref == 'refs/heads/master'
