# This is a basic workflow to help you get started with Actions

name: PySoftK testing

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    name: python ${{ matrix.python-version }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.7, 3.8, 3.9, 3.10.1]
        os: [ubuntu-latest, macOS-latest]
 
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
      - name: Setup Conda
        uses: s-weigand/setup-conda@v1
        with:
          update-conda: true
          python-version: ${{ matrix.python-version }}
          conda-channels: anaconda, conda-forge
          activate-environment: pysoftk_env
          environment-file: environment.yml
          auto-activate-base: false
      
      - name: Installation xtb
        run: |
           conda install xtb
      
      - name: Installing PySoftK
        shell: bash
        run: |
           python -m pip install wheel --user
           python -m pip install setuptools --upgrade --user
           python -m pip install . --user  
      
      - name: Run PySoftK test
        working-directory: ./test
        run: |
          python -m pip install pytest pytest-cov --user
          python -m pytest --junitxml=pytest.xml --cov-report=term-missing:skip-covered --cov=pysoftk | tee pytest-coverage.txt        
