# This is a basic workflow to help you get started with Actions

name: PySoftK testing

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        python-version: [3.9]
    name: Python ${{ matrix.python-version }} example on ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      
      - name: Install Conda (if macOS)
        if: runner.os == 'macOS'
        shell: bash
        run: |
          mkdir -p ~/miniconda3
          curl https://repo.anaconda.com/miniconda/Miniconda3-latest-MacOSX-arm64.sh -o ~/miniconda3/miniconda.sh
          bash ~/miniconda3/miniconda.sh -b -u -p ~/miniconda3
          rm ~/miniconda3/miniconda.sh
          echo "CONDA_BASE=$HOME/miniconda3" >> $GITHUB_ENV
          echo "CONDA_BIN_DIR=$CONDA_BASE/bin" >> $GITHUB_ENV
          echo "$CONDA_BIN_DIR" >> $GITHUB_PATH

          # Activate base conda environment (Corrected path with 'source')
          source $CONDA_BIN_DIR/activate base
     
      - name: Setup conda
        uses: s-weigand/setup-conda@v1
        with:
          update-conda: true
          python-version: ${{ matrix.python-version }}
          conda-channels: anaconda, conda-forge
          conda-base-path: ${{ env.CONDA_BASE }} 
      
      - name: Installation xtb
        run: |
           conda install xtb
      - name: Installation MDAnalysis
        run: |
              conda install mdanalysis
      
      - name: Installing PySoftK
        shell: bash
        run: |
           python -m pip install wheel --user
           python -m pip install setuptools --upgrade --user
           python -m pip install . --user  
               
      - name: Run PySoftK-pol test
        working-directory: ./test/test_pol
        run: |
          python -m pip install pytest pytest-cov --user
          python -m pytest --junitxml=pytest.xml --cov-report=term-missing:skip-covered --cov=pysoftk | tee pytest-coverage_1.txt
      - name: Run PySoftK-pysoftk test
        working-directory: ./test/test_pysoftk
        run: |
          python -m pip install pytest pytest-cov --user
          python -m pytest --junitxml=pytest2.xml --cov-report=term-missing:skip-covered --cov=pysoftk | tee pytest-coverage_2.txt
