# This is a basic workflow to help you get started with Actions

name: pysoftk

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    name: python ${{ matrix.python-version }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        include:
          - {python-version: "3.6", os: ubuntu-latest, documentation: True}
          - {python-version: "3.7", os: ubuntu-latest, documentation: False}
          - {python-version: "3.8", os: ubuntu-latest, documentation: True}
          - {python-version: "3.9", os: ubuntu-latest, documentation: False}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
      - name: Setup Conda
        uses: s-weigand/setup-conda@v1
        with:
          update-conda: true
          python-version: ${{ matrix.python-version }}
          conda-channels: anaconda, conda-forge
      - name: Installation xtb
        run: |
           conda install xtb
      - name: Test with pytest
        run: |
           conda install pytest
      - name: Pysoftk environment
        shell: bash {0}
        run: |
           conda create --name pysoftk_env
           conda activate pysoftk_env
