# This is a basic workflow to help you get started with Actions

name: PySoftK testing

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-12]
        python-version: [3.8, 3.9, 3.10.12]
        test_file: 
          - ${{ fromJSON((steps.list-test-files.outputs.files)) }}
          
    name: Python ${{ matrix.python-version }} example on ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Setup conda
        uses: s-weigand/setup-conda@v1
        with:
          update-conda: true
          python-version: ${{ matrix.python-version }}
          conda-channels: anaconda, conda-forge

      - name: Install jq
        run: |
           sudo apt-get update 
           sudo apt-get install -y jq
      
      - name: Installation xtb
        run: |
           conda install xtb

      - name: Installation MDAnalysis
        run: |
              conda install mdanalysis
      
      - name: Installing PySoftK
        shell: bash
        run: |
           python -m pip install wheel --user
           python -m pip install setuptools --upgrade --user
           python -m pip install . --user  
               
      - name: Run PySoftK-pol test
        working-directory: ./test/test_pol
        run: |
          python -m pip install pytest pytest-cov --user
          python -m pytest --junitxml=pytest.xml --cov-report=term-missing:skip-covered --cov=pysoftk | tee pytest-coverage_1.txt

      # List test files in test_pysoftk directory
      - name: List test files
        id: list-test-files
        run: echo "files=$(ls ./test/test_pysoftk/*.py | jq -R -s -c 'split("\n")[:-1]')" >> $GITHUB_OUTPUT
  
      - name: Run PySoftK-pysoftk test
        working-directory: ./test/test_pysoftk
        run: |
          python -m pip install pytest pytest-cov --user
          # Run the specific test file 
          python -m pytest ${{ matrix.test_file }} --junitxml=pytest.xml --cov-report=term-missing:skip-covered --cov=pysoftk | tee pytest-coverage_1.txt
      
