name: PySoftK stats

on: 
  workflow_dispatch:
jobs:
  test-curl-action:
    name: "Perform REST API"
    runs-on: ubuntu-latest
    steps:
      - name: Get Token    
        run: |
            response = $(curl  -H "Accept: application/vnd.github+json" -H "Authorization:${{ secrets.USER_NAME }}" --request GET https://api.github.com/repos/alejandrosantanabonilla/pysoftk/traffic/views)         
            echo "response from curl= $response"
