name: PySoftK stats

on: 
  workflow_dispatch:
  
  schedule:
    - cron: '*/15 17-18 * * *'
    #- cron: '1 0 16 * *'
    
jobs:
  test-curl-action:
    name: "Perform REST API"
    runs-on: ubuntu-latest
    steps:
      - name: Get Token    
        run: |
            curl  -H "Accept: application/vnd.github+json" -H "Authorization: Bearer ${{ secrets.PYSOFTK_VIEWS }}" --request GET https://api.github.com/repos/alejandrosantanabonilla/pysoftk/traffic/views -o result.json 
 
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: my-artifact
          path: ./result.json
