name: PySoftK stats

on:
  workflow_dispatch:
jobs:
  run-updater:
    runs-on: ubuntu-latest
    steps:
    - name: REST API with curl
      run: |
        curl -X GET https://api.github.com/repos/alejandrosantanabonilla/pysoftk/traffic/views
